### PR TITLE
bump pysam

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by nsoranzo** [comment]
pysam 0.15.3 wheels are now available on PyPI, thanks to https://github.com/pysam-developers/pysam/pull/814 .

**Comment by martenson** [comment]
@nsoranzo neat, thanks!

**Comment by martenson** [comment]
Jenkins still tries to build pysam though I think.

https://jenkins.galaxyproject.org/view/tool_tests/job/tool%20tests%20Galaxy%20Australia/14/console

**Comment by mvdbeek** [comment]
There's a problem with the deployment upstream, I ~~don't~~ think we should wait / try fixing upstream.

**Pull request closed without merging**
