### PR TITLE
Build uwsgi wheels for python 3 as well

### PR DESCRIPTION
**Pull request by mvdbeek**
Not sure if that's all that is needed ?

### CODE REVIEW

**Comment by mvdbeek** [comment]
hmm, doesn't look like it:
```
Running docker: docker run --cidfile __cid.txt --volume=/home/travis/build/galaxyproject/starforge-recipes:/home/travis/build/galaxyproject/starforge-recipes:ro manylinux1:d2e1d1fa5bad9e0e4c4ff23b0f3f6f2817e6d5660c272ef77bd429414cc0524d /opt/python/cp35-cp35m/bin/python -c 'import uwsgi; print(uwsgi)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_uwsgi)
```

**Comment by nsoranzo** [comment]
I think we would need to move to pyuwsgi to use Python3 wheels. IIRC, that is not straightforward though.

**Comment by mvdbeek** [comment]
the yaml parsing ? :/

**Comment by natefoo** [comment]
Superceded by galaxyproject/galaxy#8489?

**Pull request closed without merging**
