### PR TITLE
Add social-auth-core v3.1.0

### PR DESCRIPTION
**Pull request by VJalili**

### CODE REVIEW

**Comment by nsoranzo** [comment]
I don't think this is needed? https://pypi.org/project/social-auth-core/#files

**Comment by VJalili** [comment]
is it because the repo already has all the necessary wheels?

**Comment by nsoranzo** [comment]
Galaxy instructs pip to looks for wheels first at wheels.galaxyproject.org (i.e. stuff built by starforge), then at PyPI. If wheels from the original authors are already available at PyPI and they work fine, there's no reason to build them also here.

**Comment by VJalili** [comment]
Sounds great! I prefer this over our *legacy* approach.

**Pull request closed without merging**
