### PR TITLE
Build mercurial 6.0.2 wheel

### PR DESCRIPTION
**Pull request by jdavcs**

### CODE REVIEW

**Comment by nsoranzo** [comment]
That's currently used only on the dev branch of Galaxy, does it make sense? There will probably be other mercurial releases before 22.05.

**Comment by mvdbeek** [comment]
We do need it to update test.galaxyproject.org, and it'll also speed up our test builds, so I'd say yes, but I don't know about the costs (ping @natefoo).

**Comment by natefoo** [comment]
Can we just pin a version of mercurial in `dev` that wheels exist for?

**Comment by jdavcs** [comment]
> Can we just pin a version of mercurial in `dev` that wheels exist for?

You mean pin it to `mercurial_6.0.1` in `dev-requierements.txt` and `pinned-requirements.txt` on the branch we're installing on test?

**Comment by nsoranzo** [comment]
> We do need it to update test.galaxyproject.org

Is building the wheel on test.galaxyproject.org a problem? Being a test system I'd assume it can have the necessary system packages to do it.

> and it'll also speed up our test builds, so I'd say yes, but I don't know about the costs (ping @natefoo).

Wheels are cached, so it doesn't really affect CI tests.

> You mean pin it to mercurial_6.0.1 in dev-requirements.txt and pinned-requirements.txt on the branch we're installing on test?

Unless you also pin in `pyproject.toml`, that would be reverted by the next PR opened by the "Update dependencies" CI build. I don't think we want to special case mercurial for this.

**Comment by mvdbeek** [comment]
> Is building the wheel on test.galaxyproject.org a problem? Being a test system I'd assume it can have the necessary system packages to do it.

It's supposed to be a test system resembling .org, so that would be one argument against it. It's also nice to know we need to rebuild wheels before we can update main. We can deal with both of these, but I doubt the cost of building and hosting wheels is worth our time.

**Pull request merged**
