### PR TITLE
bump pysam to 0.15.1

### PR DESCRIPTION
**Pull request by martenson**
this will probably fail since we had https://github.com/galaxyproject/starforge/blob/master/wheels/build/wheels.yml#L57

### CODE REVIEW

**Comment by nsoranzo** [comment]
It seems we need only the wheels for macOS, since the Linux ones are on PyPI. Maybe we can add a new imageset to `starforge.yml`:
```
    cext-osx-wheel:
        - ci/osx-2.7
        - ci/osx-3.4
        - ci/osx-3.5
        - ci/osx-3.6
        - ci/osx-3.7
```
and use `imageset: cext-osx-wheel` in `wheels/pysam/meta.yml` .

**Comment by mvdbeek** [comment]
In any case something isn't right here, `version.sh` isn't being found, presumable because it isn't in the manifest (IOW the pypi tarball is broken). This should work though if we can take the tagged archive from github. Is there a syntax for doing that ?

**Comment by nsoranzo** [comment]
@natefoo I think we need your help here to workaround the failing `python setup.py -q wheel_info --json` for pysam (which fails for me also with its latest github version).

**Comment by nsoranzo** [comment]
@natefoo I think I may have a fix for starforge wheel_info, PR https://github.com/galaxyproject/starforge/pull/220 .

**Comment by nsoranzo** [comment]
Moved to https://github.com/galaxyproject/starforge-recipes/pull/32

**Pull request closed without merging**
